package com.cduestc.keep.mapper;

import com.cduestc.keep.model.ChooseLesson;
import com.cduestc.keep.model.ChooseLessonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChooseLessonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    long countByExample(ChooseLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int deleteByExample(ChooseLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int insert(ChooseLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int insertSelective(ChooseLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    List<ChooseLesson> selectByExample(ChooseLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    ChooseLesson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") ChooseLesson record, @Param("example") ChooseLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int updateByExample(@Param("record") ChooseLesson record, @Param("example") ChooseLessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int updateByPrimaryKeySelective(ChooseLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose_lesson
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int updateByPrimaryKey(ChooseLesson record);
}