package com.cduestc.keep.mapper;

import com.cduestc.keep.model.ShankSports;
import com.cduestc.keep.model.ShankSportsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShankSportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    long countByExample(ShankSportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    int deleteByExample(ShankSportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    int deleteByPrimaryKey(Long sportsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    int insert(ShankSports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    int insertSelective(ShankSports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    List<ShankSports> selectByExample(ShankSportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    ShankSports selectByPrimaryKey(Long sportsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") ShankSports record, @Param("example") ShankSportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    int updateByExample(@Param("record") ShankSports record, @Param("example") ShankSportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    int updateByPrimaryKeySelective(ShankSports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shank_sports
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    int updateByPrimaryKey(ShankSports record);
}