package com.cduestc.keep.mapper;

import com.cduestc.keep.model.SportsData;
import com.cduestc.keep.model.SportsDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SportsDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    long countByExample(SportsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int deleteByExample(SportsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int insert(SportsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int insertSelective(SportsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    List<SportsData> selectByExample(SportsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    SportsData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") SportsData record, @Param("example") SportsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int updateByExample(@Param("record") SportsData record, @Param("example") SportsDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int updateByPrimaryKeySelective(SportsData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sports_data
     *
     * @mbg.generated Tue May 05 16:16:31 CST 2020
     */
    int updateByPrimaryKey(SportsData record);
}