package com.cduestc.keep.dto;

import com.cduestc.keep.provider.Sports;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

@Data
public class DeliverKeepLesson implements Serializable {
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_lesson.lesson_name
     *
     * @mbg.generated Mon May 04 22:47:00 CST 2020
     */
    private String lessonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_lesson.image_url
     *
     * @mbg.generated Mon May 04 22:47:00 CST 2020
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_lesson.sports
     *
     * @mbg.generated Mon May 04 22:47:00 CST 2020
     */
    private String sports;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_lesson.hot
     *
     * @mbg.generated Mon May 04 22:47:00 CST 2020
     */
    private Integer hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_lesson.type
     *
     * @mbg.generated Mon May 04 22:47:00 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_lesson.time
     *
     * @mbg.generated Mon May 04 22:47:00 CST 2020
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_lesson.calorie
     *
     * @mbg.generated Mon May 04 22:47:00 CST 2020
     */
    private Integer calorie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_lesson.resource_url
     *
     * @mbg.generated Mon May 04 22:47:00 CST 2020
     */
    private String resourceUrl;
}
