package com.cduestc.keep.model;

import java.util.ArrayList;
import java.util.List;

public class FriendExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public FriendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFriendIdIsNull() {
            addCriterion("friend_ID is null");
            return (Criteria) this;
        }

        public Criteria andFriendIdIsNotNull() {
            addCriterion("friend_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFriendIdEqualTo(Long value) {
            addCriterion("friend_ID =", value, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdNotEqualTo(Long value) {
            addCriterion("friend_ID <>", value, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdGreaterThan(Long value) {
            addCriterion("friend_ID >", value, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdGreaterThanOrEqualTo(Long value) {
            addCriterion("friend_ID >=", value, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdLessThan(Long value) {
            addCriterion("friend_ID <", value, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdLessThanOrEqualTo(Long value) {
            addCriterion("friend_ID <=", value, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdIn(List<Long> values) {
            addCriterion("friend_ID in", values, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdNotIn(List<Long> values) {
            addCriterion("friend_ID not in", values, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdBetween(Long value1, Long value2) {
            addCriterion("friend_ID between", value1, value2, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendIdNotBetween(Long value1, Long value2) {
            addCriterion("friend_ID not between", value1, value2, "friendId");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidIsNull() {
            addCriterion("friend_friendID is null");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidIsNotNull() {
            addCriterion("friend_friendID is not null");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidEqualTo(Long value) {
            addCriterion("friend_friendID =", value, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidNotEqualTo(Long value) {
            addCriterion("friend_friendID <>", value, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidGreaterThan(Long value) {
            addCriterion("friend_friendID >", value, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidGreaterThanOrEqualTo(Long value) {
            addCriterion("friend_friendID >=", value, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidLessThan(Long value) {
            addCriterion("friend_friendID <", value, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidLessThanOrEqualTo(Long value) {
            addCriterion("friend_friendID <=", value, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidIn(List<Long> values) {
            addCriterion("friend_friendID in", values, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidNotIn(List<Long> values) {
            addCriterion("friend_friendID not in", values, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidBetween(Long value1, Long value2) {
            addCriterion("friend_friendID between", value1, value2, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendFriendidNotBetween(Long value1, Long value2) {
            addCriterion("friend_friendID not between", value1, value2, "friendFriendid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridIsNull() {
            addCriterion("friend_userID is null");
            return (Criteria) this;
        }

        public Criteria andFriendUseridIsNotNull() {
            addCriterion("friend_userID is not null");
            return (Criteria) this;
        }

        public Criteria andFriendUseridEqualTo(Long value) {
            addCriterion("friend_userID =", value, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridNotEqualTo(Long value) {
            addCriterion("friend_userID <>", value, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridGreaterThan(Long value) {
            addCriterion("friend_userID >", value, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("friend_userID >=", value, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridLessThan(Long value) {
            addCriterion("friend_userID <", value, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridLessThanOrEqualTo(Long value) {
            addCriterion("friend_userID <=", value, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridIn(List<Long> values) {
            addCriterion("friend_userID in", values, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridNotIn(List<Long> values) {
            addCriterion("friend_userID not in", values, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridBetween(Long value1, Long value2) {
            addCriterion("friend_userID between", value1, value2, "friendUserid");
            return (Criteria) this;
        }

        public Criteria andFriendUseridNotBetween(Long value1, Long value2) {
            addCriterion("friend_userID not between", value1, value2, "friendUserid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table keep_friend
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 19 02:58:57 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table keep_friend
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}