package com.cduestc.keep.model;

public class PlanProgress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_progress.plan_ProgressID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    private Long planProgressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_progress.owner_ID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    private Long ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_progress.start_planID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    private Long startPlanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_progress.current_state
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    private Long currentState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_progress.end_planID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    private Long endPlanid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_progress.plan_ProgressID
     *
     * @return the value of plan_progress.plan_ProgressID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public Long getPlanProgressid() {
        return planProgressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_progress.plan_ProgressID
     *
     * @param planProgressid the value for plan_progress.plan_ProgressID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public void setPlanProgressid(Long planProgressid) {
        this.planProgressid = planProgressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_progress.owner_ID
     *
     * @return the value of plan_progress.owner_ID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_progress.owner_ID
     *
     * @param ownerId the value for plan_progress.owner_ID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_progress.start_planID
     *
     * @return the value of plan_progress.start_planID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public Long getStartPlanid() {
        return startPlanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_progress.start_planID
     *
     * @param startPlanid the value for plan_progress.start_planID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public void setStartPlanid(Long startPlanid) {
        this.startPlanid = startPlanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_progress.current_state
     *
     * @return the value of plan_progress.current_state
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public Long getCurrentState() {
        return currentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_progress.current_state
     *
     * @param currentState the value for plan_progress.current_state
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public void setCurrentState(Long currentState) {
        this.currentState = currentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_progress.end_planID
     *
     * @return the value of plan_progress.end_planID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public Long getEndPlanid() {
        return endPlanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_progress.end_planID
     *
     * @param endPlanid the value for plan_progress.end_planID
     *
     * @mbg.generated Sat Feb 15 21:07:37 CST 2020
     */
    public void setEndPlanid(Long endPlanid) {
        this.endPlanid = endPlanid;
    }
}