package com.cduestc.keep.model;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_post.post_ID
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_post.owner_ID
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    private Long ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_post.image_url
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_post.video_url
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_post.create_date
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keep_post.description
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keep_post.post_ID
     *
     * @return the value of keep_post.post_ID
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keep_post.post_ID
     *
     * @param postId the value for keep_post.post_ID
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keep_post.owner_ID
     *
     * @return the value of keep_post.owner_ID
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keep_post.owner_ID
     *
     * @param ownerId the value for keep_post.owner_ID
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keep_post.image_url
     *
     * @return the value of keep_post.image_url
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keep_post.image_url
     *
     * @param imageUrl the value for keep_post.image_url
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keep_post.video_url
     *
     * @return the value of keep_post.video_url
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keep_post.video_url
     *
     * @param videoUrl the value for keep_post.video_url
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keep_post.create_date
     *
     * @return the value of keep_post.create_date
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keep_post.create_date
     *
     * @param createDate the value for keep_post.create_date
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keep_post.description
     *
     * @return the value of keep_post.description
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keep_post.description
     *
     * @param description the value for keep_post.description
     *
     * @mbg.generated Sat Apr 04 19:47:10 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}