package com.cduestc.keep.model;

public class SportWear {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sports_wear.wear_ID
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    private Long wearId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sports_wear.wear_name
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    private String wearName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sports_wear.image_url
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sports_wear.sex
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sports_wear.brand
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sports_wear.price
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sports_wear.description
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sports_wear.storage
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    private Integer storage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sports_wear.wear_ID
     *
     * @return the value of sports_wear.wear_ID
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public Long getWearId() {
        return wearId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sports_wear.wear_ID
     *
     * @param wearId the value for sports_wear.wear_ID
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setWearId(Long wearId) {
        this.wearId = wearId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sports_wear.wear_name
     *
     * @return the value of sports_wear.wear_name
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public String getWearName() {
        return wearName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sports_wear.wear_name
     *
     * @param wearName the value for sports_wear.wear_name
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setWearName(String wearName) {
        this.wearName = wearName == null ? null : wearName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sports_wear.image_url
     *
     * @return the value of sports_wear.image_url
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sports_wear.image_url
     *
     * @param imageUrl the value for sports_wear.image_url
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sports_wear.sex
     *
     * @return the value of sports_wear.sex
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sports_wear.sex
     *
     * @param sex the value for sports_wear.sex
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sports_wear.brand
     *
     * @return the value of sports_wear.brand
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sports_wear.brand
     *
     * @param brand the value for sports_wear.brand
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sports_wear.price
     *
     * @return the value of sports_wear.price
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sports_wear.price
     *
     * @param price the value for sports_wear.price
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sports_wear.description
     *
     * @return the value of sports_wear.description
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sports_wear.description
     *
     * @param description the value for sports_wear.description
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sports_wear.storage
     *
     * @return the value of sports_wear.storage
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public Integer getStorage() {
        return storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sports_wear.storage
     *
     * @param storage the value for sports_wear.storage
     *
     * @mbg.generated Sun Apr 19 02:58:57 CST 2020
     */
    public void setStorage(Integer storage) {
        this.storage = storage;
    }
}